### ISSUE TITLE
Tabs versus spaces

### ISSUE THREAD

**Issue by schneems** [ioquatix/rack-freeze#2]
First, i love this library. You are amazing and this is great. I just had a conversation with someone the other day about writing something like this, and here it is already written!

Minor question/nit. I was looking through the internals, they're very clean. I was however wondering if we could switch from tabs to 2 spaces instead? It's not a requirement by any stretch, but 2 spaces seems to be the community norm and as you start getting contributions you'll likely end up with a miss-mash of tabs and spaces.

Would you accept a pull request that converted all the tabs to 2 spaces?

**Comment by attilagyorffy** [comment]
🍿

**Comment by jefersontonin** [comment]
🍿

**Comment by charlespeach** [comment]
🍿

**Comment by juddey** [comment]
:popcorn:

**Comment by sfcgeorge** [comment]
The overarching issue might be ensuring consistency in coding style. Following community "standards" is a great suggestion too (I also use 2 spaces) but either way someone will come along and write code like:

```ruby
?I " love " << %!Ruby!
```

Me, I would write code like that. 

So a PR to add Rubocop & Travis could be even better. Or Reek (I just don't like the mental image of smelly code). But whatever, maintainer can choose whether they'd like to think about Robocop or odours when linting their code, and add a custom rule for their choice of spaces / tabs. 🍿

**Comment by ioquatix** [comment]
Thanks for your positive feedback.

@schneems Yes, I'd accept a PR converting spaces to tabs. I'll even merge it provided it doesn't make the code objectively worse in any way, excepting the change itself. However, if I come to work on this code again in the future and the spaces/tabs gets in the way of my work, I may revert it at that time. I'd be happy to see more people able to contribute, and if you think tabs/spaces is a significant factor stoping people from contributing, I'm happy to run with that hypothesis and see where it leads. I'm all for evidence based decisions.

@sfcgeorge I like how you are thinking. I've seen code become objectively worse after applying Rubocop's suggestions. As you've pointed out, good code isn't simply about applying a heuristic model to the AST.

I'm going to now go out on a limb here to explain my motivations. I've listened to yours, and I've accepted your hypothesis. If you like you can listen to mine. I'm not giving you more fuel for an argument, just really matter of factly stating why I do what I do. You can understand that my decision is not just arbitrary and the kinds of things I'll be considering going forward.

For me, at about the age of 15 (2000) when I was writing PHP and C++, I made an objective decision that tabs suited me better, and made more sense, and I've kept at that since then, across quite a few different languages, across several hundred projects. So, all my code, excepting personal improvement over time, is internally consistent. Whether it's consistent with the flavour of the day within a given community, has not really been something I've been concerned about.

Technically, for me, tabs are the ideal semantic unit of indentation. Spaces are a lossy form of indentation. You can see this by writing a function to convert tabs to spaces (easy), and then spaces to tabs (hard edge cases). Is this relevant? Yes, to me: I write code to generate/manipulate code and it's always better when you can assume an indent is a single tab. It's easier to indent or outdent existing code, it's easier to match indentation vs alignment. 

Other place you can see this is editor support. Tabs just seem to work correctly out of the box on all platforms I've ever worked on, but a lot of editors where I've done the same thing with spaces, I've found I have to press backspace several times to outdent. As a teacher, I've seen tons of people struggle with this, bashing on the space bar or backspace a ton of times for what should be a trivial operation. People say spaces work better but for me they seem like the lowest common denominator that work everywhere but with pretty severe functional and technical caveats.

I prefer how tabs are visualised in editors (little arrows which clearly mark a single unit of indentation), and deliberately have my editor set up to change tab width based on editor width (responsive indentation width). I like to change tab width between my laptop and desktop (30" display) and this isn't possible when using spaces for indentation.

You refer to community standards. But have you looked at how MRI indents the C code? There are a ton of different ways to indent code and I think ultimately, we simply have to accept that the indentation style is only one facet of code quality. As you've said, and I appreciate, that the quality of the code in this gem is my normal high standard. Changing the style of indentation won't affect that.

**Comment by ioquatix** [comment]
The outcome of this is that we converted tabs to spaces here: https://github.com/ioquatix/rack-freeze/pull/3

So far no tangible changes to the project have been observed.
